const taskNames = require("hardhat/builtin-tasks/task-names");

// This task is called for each generated artifact, and it receivese three inputs:
// * The `sourceName`, which roughly corresponds to the relative path to the solidity file
// * The `contractName`, which is the name of the contract
// * The `contractOutput`, which is basically `compilerOutput.contracts[sourceName][contractName]`
subtask(
  taskNames.TASK_COMPILE_SOLIDITY_GET_ARTIFACT_FROM_COMPILATION_OUTPUT,
  async ({ sourceName, contractName, contractOutput }, hre, runSuper) => {
    // Get the default artifact generated by Hardhat
    const artifact = await runSuper();

    // Modify it however you want
    artifact.devdoc = contractOutput.devdoc
    artifact.userdoc = contractOutput.userdoc

    return artifact;
  }
);

module.exports = {
  solidity: {
    version: "0.7.3",
    settings: {
      outputSelection: {
        "*": {
          "*": ["devdoc", "userdoc"]
        }
      }
    }
  }
};
